name: workflow-dispatch-test

on:
  workflow_dispatch:
    inputs:
      hoge:
        description: "実行時にパラメータを渡すことができます"
        required: true
        default: "fuga"

jobs:
  hello:
    runs-on: ubuntu-latest  # 最新のUbuntu環境でjobを実行
    steps:
    - name: Echo input value
      run: echo "${{ github.event.inputs.hoge }}"
